# Generated by Django 5.0.7 on 2024-08-04 00:29

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('eliminado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('idDiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('nivelGlucosa', models.FloatField(validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(300.0)])),
                ('icm', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(100.0)])),
                ('estadoFumador', models.CharField(max_length=200)),
                ('tipoTrabajo', models.CharField(max_length=200)),
                ('prediccion', models.BooleanField(blank=True, default=False, null=True)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2024, 8, 3, 19, 29, 36, 268468))),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadapp.paciente')),
            ],
        ),
    ]
