# Generated by Django 5.0.7 on 2024-08-04 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0002_alter_diagnostico_fecharegistro_alter_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 18, 21, 46, 43980)),
        ),
    ]
