# Generated by Django 5.0.7 on 2024-08-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0004_alter_diagnostico_fecharegistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='cardiopatia',
            new_name='Cardiopatia',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='estadoFumador',
            new_name='EstadoFumador',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='hipertension',
            new_name='Hipertension',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='icm',
            new_name='ICM',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='nivelGlucosa',
            new_name='Nivel_GlucosaPromedio',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='tipoTrabajo',
            new_name='TipoTrabajo',
        ),
    ]
