# Generated by Django 5.0.7 on 2024-08-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0006_diagnostico_edad_diagnostico_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='Edad',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='EstadoFumador',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='Genero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='TipoTrabajo',
            field=models.CharField(max_length=200),
        ),
    ]
