# Generated by Django 5.0.7 on 2024-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0007_alter_diagnostico_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='Edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
