# Generated by Django 5.0.7 on 2024-08-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0008_alter_diagnostico_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='EstadoFumador',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='TipoTrabajo',
            field=models.IntegerField(max_length=200),
        ),
    ]
