# Generated by Django 5.0.7 on 2024-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0009_alter_diagnostico_estadofumador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='EstadoFumador',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='TipoTrabajo',
            field=models.CharField(max_length=200),
        ),
    ]
