# Generated by Django 5.0.7 on 2024-08-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0010_alter_diagnostico_estadofumador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
