# Generated by Django 5.0.7 on 2024-08-13 05:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0011_alter_paciente_celular_alter_paciente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico2',
            fields=[
                ('idDiagnostico2', models.AutoField(primary_key=True, serialize=False)),
                ('Genero', models.CharField(blank=True, max_length=200, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Hipertension', models.FloatField(default=False)),
                ('Cardiopatia', models.FloatField(default=False)),
                ('TipoTrabajo', models.CharField(max_length=200)),
                ('Nivel_GlucosaPromedio', models.FloatField(validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(300.0)])),
                ('ICM', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(100.0)])),
                ('prediccion', models.FloatField(blank=True, default=False, null=True)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadapp.paciente')),
            ],
        ),
    ]
