# Generated by Django 5.0.7 on 2024-08-13 05:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0011_alter_paciente_celular_alter_paciente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico3',
            fields=[
                ('idDiagnostico3', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(blank=True, max_length=200, null=True)),
                ('edadRango', models.IntegerField(blank=True, null=True)),
                ('etnia', models.CharField(blank=True, max_length=200, null=True)),
                ('fumador', models.FloatField(default=False)),
                ('bebedorFrecuente', models.FloatField(default=False)),
                ('actividadFisica', models.FloatField(default=False)),
                ('horasDormidas', models.IntegerField(blank=True, null=True)),
                ('prediccion', models.FloatField(blank=True, default=False, null=True)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadapp.paciente')),
            ],
        ),
    ]
