# Generated by Django 5.0.7 on 2024-08-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadapp', '0012_diagnostico2'),
        ('seguridadapp', '0012_diagnostico3'),
    ]

    operations = [
    ]
